### ISSUE TITLE
miss some movie's ID

### ISSUE THREAD

**Issue by t1ina2003** [t1ina2003/pycrawler#5]
some movies don't have trailer, so get movie id in another way
https://github.com/t1ina2003/pycrawler/blob/84b369574885fd302ae88121c38ae15e92410142/01_yahoomovie.py#L24-L24

**Comment by no543** [comment]
https://github.com/no543/pycrawler/blob/21bc183cf4091b3c37373124257427519fc4f941/01_yahoomovie.py#L20-L22

**Comment by no543** [comment]
https://github.com/t1ina2003/pycrawler/blob/dd124af0a199bdef6b2a86586a51d2149cf5ea9d/01_yahoomovie.py#L20
